from django.urls import path

from tasks.views import (index,
                         TaskListView,
                         WorkerListView,
                         TaskDetailView,
                         TaskCreateView,
                         TaskUpdateView,
                         TaskDeleteView,
                         WorkerDetailView,
                         WorkerDeleteView,
                         WorkerCreateView,
                         PositionListView,
                         PositionDetailView,
                         PositionCreateView,
                         PositionUpdateView,
                         TaskTypeListView,
                         TaskTypeDetailView,
                         TaskTypeCreateView,
                         TaskTypeUpdateView,
                         TagListView,
                         TagDetailView,
                         TagCreateView,
                         TagUpdateView,
                         TagDeleteView,
                         ProjectListView,
                         ProjectDetailView,
                         ProjectCreateView,
                         ProjectUpdateView,
                         ProjectDeleteView,
                         TeamListView,
                         TeamDetailView,
                         TeamUpdateView,
                         TeamDeleteView,
                         TeamCreateView,
                         PositionDeleteView,
                         TaskTypeDeleteView)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/update/<int:pk>", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/delete/<int:pk>", TaskDeleteView.as_view(), name="task-delete"),

    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),

    path("workers/delete/<int:pk>", WorkerDeleteView.as_view(), name="worker-delete"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/<int:pk>", PositionDetailView.as_view(), name="position-detail"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path("positions/update/<int:pk>", PositionUpdateView.as_view(), name="position-update"),
    path("positions/delete/<int:pk>", PositionDeleteView.as_view(), name="position-delete"),
    path("task_types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task_types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task_types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path("task_types/update/<int:pk>/", TaskTypeUpdateView.as_view(), name="task-type-update"),
    path("task_types/delete/<int:pk>/", TaskTypeDeleteView.as_view(), name="task-type-delete"),

    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/update/<int:pk>/", ProjectUpdateView.as_view(), name="project-update"),
    path("projects/delete/<int:pk>/", ProjectDeleteView.as_view(), name="project-delete"),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/update/<int:pk>/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/delete/<int:pk>/", TeamDeleteView.as_view(), name="team-delete"),

]

app_name = "tasks"
