# Generated by Django 5.2.7 on 2026-02-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_options_alter_worker_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                default="Unknown",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workers",
                to="tasks.position",
            ),
        ),
    ]
