# Generated by Django 5.2.7 on 2026-02-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
